language: java
sudo: false
install: true
script:
    - ant jar
    - cd dist
    - zip -r ../binary-package.zip *
    - cd ..
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN 
  keep-history: true
  file: $TRAVIS_BUILD_DIR/binary-package.zip
  on:
    branch: master
    tags: true
